"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Download, Loader2 } from "lucide-react";

export default function AIReportGenerator({ election }: { election: any }) {
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState<string | null>(null);

  const generateReport = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2000));
    
    const turnout = election.totalVoters > 0 ? Math.round((election.totalVotes / election.totalVoters) * 100) : 0;
    const winner = election.candidates?.sort((a: any, b: any) => (b.votes || 0) - (a.votes || 0))[0];
    const margin = election.candidates?.length > 1 
      ? Math.abs((election.candidates[0]?.votes || 0) - (election.candidates[1]?.votes || 0)) 
      : 0;

    const reportText = `
EXECUTIVE SUMMARY
=================
Election: ${election.title}
Type: ${election.type?.replace(/_/g, " ")}
Date: ${new Date(election.startDate).toLocaleDateString()} - ${new Date(election.endDate).toLocaleDateString()}

KEY METRICS
===========
• Total Registered Voters: ${election.totalVoters?.toLocaleString() || "N/A"}
• Total Votes Cast: ${election.totalVotes?.toLocaleString() || "N/A"}
• Voter Turnout: ${turnout}%
• Candidates: ${election.candidates?.length || 0}
• Winning Margin: ${margin.toLocaleString()} votes

${winner ? `WINNER: ${winner.name} (${winner.position}) with ${winner.votes?.toLocaleString() || 0} votes` : "Results pending"}

AI ANALYSIS
===========
• Turnout Assessment: ${turnout > 65 ? "Strong participation indicates high voter engagement." : turnout > 40 ? "Moderate turnout. Consider engagement campaigns for future elections." : "Low turnout detected. Recommend investigating barriers to participation."}
• Election Integrity: ${turnout > 0 ? "Voting patterns appear normal. No anomalies detected." : "Insufficient data for integrity analysis."}
• Recommendation: ${turnout > 0 ? "Archive results and publish transparency report." : "Extend voting period or send reminder notifications."}

Generated by BallotChain AI • ${new Date().toISOString()}
    `.trim();

    setReport(reportText);
    setGenerating(false);
  };

  const downloadReport = () => {
    if (!report) return;
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = election.title?.replace(/\s/g, "-") + "-ai-report.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass rounded-2xl p-6">
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}>
        <div style={{ width: 36, height: 36, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, background: "rgba(245,158,11,0.15)", color: "#F59E0B" }}>
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h3 className="syne" style={{ fontSize: 14, fontWeight: 700, color: "#fff" }}>AI Report Generator</h3>
          <p style={{ fontSize: 11, color: "rgba(255,255,255,0.4)" }}>Automated executive summary</p>
        </div>
      </div>

      <button onClick={generateReport} disabled={generating}
        className="btn-gold" style={{ width: "100%", padding: "10px", borderRadius: 10, fontSize: 12, fontWeight: 600, color: "#1a1a1a", border: "none", cursor: "pointer", marginBottom: 12, background: "linear-gradient(135deg, #F59E0B, #FBBF24)" }}>
        {generating ? (
          <><Loader2 className="w-4 h-4 inline mr-1 animate-spin" /> Generating...</>
        ) : (
          <><FileText className="w-4 h-4 inline mr-1" /> Generate AI Report</>
        )}
      </button>

      {report && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <div style={{ padding: 14, borderRadius: 12, background: "rgba(255,255,255,0.03)", border: "0.5px solid rgba(255,255,255,0.06)", maxHeight: 300, overflowY: "auto", marginBottom: 8 }}>
            <pre style={{ fontSize: 11, color: "rgba(255,255,255,0.6)", fontFamily: "monospace", whiteSpace: "pre-wrap", margin: 0, lineHeight: 1.6 }}>
              {report}
            </pre>
          </div>
          <button onClick={downloadReport}
            className="btn-blue" style={{ width: "100%", padding: "10px", borderRadius: 10, fontSize: 12, fontWeight: 600, color: "#fff", border: "none", cursor: "pointer" }}>
            <Download className="w-4 h-4 inline mr-1" /> Download Report
          </button>
        </motion.div>
      )}
    </div>
  );
}